apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-beat
  labels:
    app: worker-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-beat
  template:
    metadata:
      labels:
        app: worker-beat
    spec:
      initContainers:
        - name: wait-middleware
          image: busybox
          envFrom:
            - configMapRef:
                name: lomva-config
          command:
            - sh
            - -c
            - |
              until nc -z "$DB_HOST" "$DB_PORT" && nc -z redis 6379; do
                echo waiting for "$DB_HOST:$DB_PORT"/redis
                sleep 2
              done
      containers:
        - name: worker-beat
          image: langgenius/dify-api
          envFrom:
            - configMapRef:
                name: lomva-config
            - secretRef:
                name: lomva-secret
          env:
            - name: MODE
              value: beat
