apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa-ai

resources:
  - namespace.yaml
  - middleware/redis.yaml
  - middleware/weaviate.yaml
  - proxy/ssrf-proxy.yaml
  - proxy/agent-ssrf-proxy.yaml
  - runtime/plugin-daemon.yaml
  - runtime/sandbox.yaml
  - runtime/local-sandbox.yaml
  - app/init-job.yaml
  - app/api.yaml
  - app/api-websocket.yaml
  - app/worker.yaml
  - app/worker-beat.yaml
  - app/web.yaml
  - app/agent-backend.yaml
  - gateway/nginx.yaml


configMapGenerator:
  - name: lomva-config
    envs:
      - config/lomva-config.env
  - name: lomva-web-config
    envs:
      - config/web-config.env
  - name: lomva-ssrf-proxy-config
    files:
      - squid.conf.template=config/squid/ssrf-squid.conf.template
      - dify_common.conf.template=config/squid/dify_common.conf.template
  - name: lomva-agent-ssrf-proxy-config
    files:
      - squid.conf.template=config/squid/agent-squid.conf.template
      - dify_common.conf.template=config/squid/dify_common.conf.template
  - name: lomva-sandbox-config
    files:
      - config.yaml=config/sandbox/config.yaml
  - name: lomva-nginx-config
    files:
      - nginx.conf=config/nginx/nginx.conf
      - proxy.conf=config/nginx/proxy.conf
      - default.conf=config/nginx/default.conf

secretGenerator:
  - name: lomva-secret
    type: Opaque
    envs:
      - config/lomva-secret.env

images:
  - name: langgenius/dify-api
    newTag: 1.16.1
  - name: langgenius/dify-web
    newTag: 1.16.1
  - name: langgenius/dify-sandbox
    newTag: 0.2.15
  - name: langgenius/dify-agent-local-sandbox
    newTag: 1.16.1
  - name: langgenius/dify-plugin-daemon
    newTag: 0.6.10-local
  - name: langgenius/dify-agent-backend
    newTag: 1.16.1
  - name: postgres
    newTag: 15-alpine
  - name: redis
    newTag: 6-alpine
  - name: semitechnologies/weaviate
    newTag: 1.27.0
  - name: ubuntu/squid
    newTag: latest
  - name: nginx
    newTag: 1.27-alpine
  - name: busybox
    newTag: "1.36"
